# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=6),
            preserve_default=False,
        ),
    ]
