# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_producto_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='iva',
            field=models.FloatField(),
        ),
    ]
